name: USB Audio Build and Test

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'usb-audio/**'
      - '.github/workflows/usb-audio.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'usb-audio/**'
      - '.github/workflows/usb-audio.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install ESP-IDF
      uses: espressif/install-esp-idf-action@v1
      with:
        version: 'v5.5.1'
        
    - name: Build project
      working-directory: ./usb-audio
      run: |
        idf.py set-target esp32s3
        idf.py build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: usb-audio-firmware
        path: usb-audio/build/usb-mic2.bin
        retention-days: 7
